


HOSTNAME = "127.0.0.1"
PORT = '3306'
DATABASE = 'ginger'
USERNAME = 'root'
PASSWORD = "302811"
DB_URL = "mysql+cymysql://{}:{}@{}:{}/{}".format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URL

SECRET_KEY = 'TVQLNDAU7UYVPBZFXUL2JQA27CCG5ABUD3UQ2TWPE2CJFTHHIQAQ===='